### ISSUE TITLE
设置背景图片

### ISSUE THREAD

**Issue by PBlithe** [PBlithe/Blog#6]
## 设置背景图片

问题：

在做前端的过程中，我尝试给body和div设置背景。我的思路是用css改变他们的样式。我遇到了一下问题：

1. 不知道导入背景图片的css样式怎么写
2. 知道css样式怎么写之后仍无法显示背景图片

## 关于问题一

以设置body背景为例

```css
body{
    width: 100%;
    height: 100%;
    background-image: url("static/img/bg5.jpg");//url()为图片路径
    background-repeat: no-repeat;
	background-size: 100% 100%;
}
```

## 关于问题二

虽然设置了背景图片，但是body和div框只有宽度没有高度。因此需要手动设置div或body的宽度和高度。

以给body设置背景图片为例子。以下是完整版代码：

```css
body{
    width: 100%;
    height: 100%;
    background-image: url("static/img/bg5.jpg");
    background-repeat: no-repeat;
	background-size: 100% 100%;
}
html,body{
	height:100%;
}
```
